### ISSUE TITLE
Bug in setup.py?

### ISSUE THREAD

**Issue by araichev** [Jaymon/dump#13]
Hi there,

I installed Dump inside a Python 3.6.5 virtual environment using ``pipenv install dump``.
Then i typed ``dump`` on the command line and got the following error.

```
Traceback (most recent call last):
  File "/home/araichev/.virtualenvs/strava-594zSWP6/bin/dump", line 7, in <module>
    from dump import console
ImportError: cannot import name 'console'
```

**Comment by Jaymon** [comment]
Ugh, my bad, I'm not sure how I missed that, I've fixed it and updated pypi. Thanks for the heads up
